name: Random Reviewer

on:
  pull_request:
    branches:
      - master

jobs:
  random-reviewer:
    runs-on: ubuntu-latest
    env:
    steps:
      - name: Assign the reviewer randomly
        uses: JedBeom/random-reviewer-discord@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          candidates: ${{ secrets.CANDIDATES }}
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          template: "<@{userID}> 님이 리뷰어로 당첨! [PR #{prNumber}]({prLink})"
